# Generated by Django 3.1 on 2020-08-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='code',
            field=models.CharField(max_length=40, null=True, verbose_name='编号'),
        ),
    ]
