# Generated by Django 3.1 on 2020-08-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0002_region_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=50, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='area',
            name='short_name',
            field=models.CharField(max_length=50, verbose_name='简称'),
        ),
        migrations.AlterField(
            model_name='street',
            name='name',
            field=models.CharField(max_length=50, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='street',
            name='short_name',
            field=models.CharField(max_length=50, verbose_name='简称'),
        ),
    ]
