# Generated by Django 3.1 on 2020-08-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0003_auto_20200813_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=50, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='region',
            name='short_name',
            field=models.CharField(max_length=50, verbose_name='简称'),
        ),
    ]
